from Model import Grid

thing = Grid()

print(thing.grid)
thing.add_number()
thing.add_number()
thing.add_number()
thing.add_number()
thing.add_number()
thing.add_number()
thing.add_number()
thing.add_number()
thing.add_number()
thing.add_number()
thing.add_number()
print(thing.grid)
thing.move_left()
print(thing.grid)
thing.move_right()
print(thing.grid)
thing.move_up()
print(thing.grid)
thing.move_down()
print(thing.grid)